### ISSUE TITLE
Add parseFloat befire toFixed

### ISSUE THREAD

**Issue by deathg0d** [jczaplew/geojson-precision#3]
Hi, is it possible to add parseFloat in the parse function before toFixed so that error is not thrown even if the coordinates are in string format? i.e. should work for `32.32121` as well as `"32.32121"`

`return 1 * parseFloat(e).toFixed(precision);`

I would change it in the module myself but don't want to mess up on updates through npm.

**Comment by jczaplew** [comment]
geojson-precision assumes that the input is a valid GeoJSON, and coordinates and strings would not be a valid GeoJSON
